version: '3.7'
services:

  qgisserver:
    image: elpaso/qgis-server-standalone:latest
    init: true
    ports:
    - "${PUBLIC_PORT}:${PUBLIC_PORT}"
    environment:
      - QGIS_SERVER_MAX_THREADS=-1
      # Mounted in ${PLUGINS_VOLUME} volume
      - QGIS_PLUGINPATH=/plugins
      - QGIS_SERVER_IGNORE_BAD_LAYERS=1
      - QGIS_SERVER_API_RESOURCES_DIRECTORY=${QGIS_SERVER_API_RESOURCES_DIRECTORY}
      # Landing page plugin projects directory
      - QGIS_SERVER_PROJECTS_DIRECTORIES=${QGIS_SERVER_PROJECTS_DIRECTORIES}
      - QGIS_SERVER_PROJECTS_PG_CONNECTIONS=postgresql://postgis:5432?user=${POSTGRES_USER}&password=${POSTGRES_PASS}&sslmode=disable&dbname=${POSTGRES_DBNAME}&schema=public
    command: >
        bash -c "/usr/bin/xvfb-run -a /usr/bin/qgis_mapserver -l ${QGIS_SERVER_LOG_LEVEL} ${PUBLIC_HOSTNAME}:${PUBLIC_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/shared-volume
      - ${PLUGINS_VOLUME}:/plugins
    networks:
      internal:

  postgis:
    image: kartoza/postgis:12.1
    ports:
    - "55432:5432"
    environment:
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/var/lib/postgresql
    networks:
      internal:
        aliases:
          - ${PUBLIC_HOSTNAME}

networks:
  internal:
